Authentication
veterinary-salons/backend pull request #1
Opened 2023-08-27 21:47 UTC by sumnslight

Так как оказалось, что у пользователя может быть только один аккаунт(одна роль), надо было переделать модели. Добавил стандартную аутентификацию с токеном из rest_framework'а с изменениями однако дефолтного сериализатора формы получения токена, чтобы он принимал email вместо username

2023-08-28 07:33 UTC, Yohimbe227 commented on backend/users/models.py
> +        if extra_fields.setdefault("is_staff", True) is not True:
может просто is False?

2023-08-28 07:33 UTC, Yohimbe227 commented on backend/users/models.py
> +        if extra_fields.setdefault("is_superuser", True) is not True:
Аналогично.

2023-08-28 07:44 UTC, Yohimbe227 commented on backend/backend/settings.py
> +    "rest_framework.authtoken",
Может таки через allauth делать? А то потом вход через соцсети может быть тяжко прикручивать.

2023-08-28 07:46 UTC, Yohimbe227 commented on backend/users/serializers.py
> +from .models import User, CustomerProfile, SupplierProfile
Имхо, тут везде лучше использовать абсолютные импорты. Структура может меняться и в таком виде все уплывет.

2023-08-28 07:49 UTC, Yohimbe227 requested changes
С выбором либы авторизации надо подумать. Потом исправлять будет больно.

2023-08-30 17:47 UTC, sumnslight commented
на роль либы авторизации можно взять drf-social-oauth2, там всё есть.

2023-08-30 17:47 UTC, closed without merging

2023-08-30 17:47 UTC, sumnslight commented
ok